fixtures:
  symlinks:
    harden_windows_server: "#{source_dir}"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: '4.25.1'
    local_security_policy:
      repo: "ayohrling/local_security_policy"
      ref: '0.6.3'
    registry:
      repo: "puppetlabs/registry"
      ref: '2.0.2'
    auditpol:
      repo: 'autostructure/auditpol'
      red: '1.0.0'
